"""change database

Revision ID: 263bb8ea167a
Revises: 
Create Date: 2020-09-15 15:06:42.723754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263bb8ea167a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_post'), 'posts', ['post'], unique=True)
    op.create_table('types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_type'), 'types', ['type'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('user_login', sa.String(length=64), nullable=False),
    sa.Column('user_post', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_post'], ['posts.post'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_user_login'), 'staff', ['user_login'], unique=True)
    op.create_index(op.f('ix_staff_user_name'), 'staff', ['user_name'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_type', sa.String(length=64), nullable=True),
    sa.Column('car_plate_number', sa.String(length=10), nullable=False),
    sa.Column('car_status', sa.String(length=30), nullable=False),
    sa.Column('date_of_last_inspection', sa.DateTime(), nullable=True),
    sa.Column('clean_status', sa.String(length=30), nullable=False),
    sa.Column('tech_status', sa.String(length=30), nullable=False),
    sa.Column('last_staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_type'], ['types.type'], ),
    sa.ForeignKeyConstraint(['last_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_car_plate_number'), 'cars', ['car_plate_number'], unique=True)
    op.create_table('personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id_car', sa.Integer(), nullable=True),
    sa.Column('id_staff', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_car'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['id_staff'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting')
    op.drop_table('personal')
    op.drop_index(op.f('ix_cars_car_plate_number'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_staff_user_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_user_login'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_types_type'), table_name='types')
    op.drop_table('types')
    op.drop_index(op.f('ix_posts_post'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
